version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      pip-dep:
        patterns:
          - "*"
        exclude-patterns:
          - "starlette"
    ignore:
      - dependency-name: "cryptography"
  - package-ecosystem: "pip"
    directory: "/reader"
    schedule:
      interval: "weekly"
    groups:
      pip-dep:
        patterns:
          - "*"
        exclude-patterns:
          - "starlette"
    ignore:
      - dependency-name: "cryptography"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      npm-dep:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
