version: 3.8

lockoff:
  image:
  container_name: lockoff
  restart: always
  network_mode: host
  volumes:
    - $PWD/database:/database
  environment:
    - TZ=Europe/Copenhagen
    - klubmodul_username=REPLACE
    - klubmodul_password=REPLACE
    - database_url=sqlite:///database/data.db
  devices:
    - /dev/serial/by-path/...:/dev/ttyACM0
    - /dev/serial/by-path/...:/dev/ttyACM1
  healthcheck:
    test: "curl --fail http://localhost:80/healtz || exit 1"
    interval: 60s
    timeout: 3s
    start_period: 20s
    retries: 5