version: "3.8"
services:
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} ping | grep PONG
      interval: 10s
      timeout: 3s
      retries: 5
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  lockoff:
    image: jensimik/lockoff:latest
    container_name: lockoff
    restart: always
    volumes:
      - $PWD/db_member.json:/db_member.json
      - $PWD/db_dayticket.json:/db_dayticket.json
      - $PWD/door.log:/door.log
    environment:
      - prod=1
      - tz=Europe/Copenhagen
      - klubmodul_base_url=${KLUBMODUL_BASE_URL}
      - klubmodul_username=${KLUBMODUL_USERNAME}
      - klubmodul_password=${KLUBMODUL_PASSWORD}
      - opticon_url=/dev/OPTICON
      - redis_url=redis://:${REDIS_PASSWORD}@redis
    group_add:
      - dialout
    devices:
      - /dev/OPTICON:/dev/OPTICON
    depends_on:
      - redis
    healthcheck:
      test: "curl --fail http://localhost:80/healtz || exit 1"
      interval: 60s
      timeout: 3s
      start_period: 20s
      retries: 5