version: "3.8"  
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} ping | grep PONG
      interval: 10s
      timeout: 3s
      retries: 5
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  litestream:
    image: litestream/litestream
    container_name: litestream
    restart: always
    command: >
      replicate
    volumes:
      - $PWD/db:/db
      - $PWD/litestream.yml:/etc/litestream.yml:ro
    environment:
      - LITESTREAM_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - LITESTREAM_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  lockoff-backend:
    image: jensimik/lockoff-backend:latest
    container_name: lockoff-backend
    restart: always
    volumes:
      - $PWD/db:/db
      - $PWD/secret:/secret:ro
    environment:
      - tz=Europe/Copenhagen
      - db_file=/db/lockoff
      - klubmodul_base_url=${KLUBMODUL_BASE_URL}
      - klubmodul_username=${KLUBMODUL_USERNAME}
      - klubmodul_password=${KLUBMODUL_PASSWORD}
      - redis_url=${REDIS_URL}
      - jwt_secret=${JWT_SECRET}
      - secret=${SECRET}
      - dl_secret=${DL_SECRET}
      - apple_pass_key_password=${APPLE_PASS_KEY_PASSWORD}
      - admin_user_ids=${ADMIN_USER_IDS}
      - hash_salt=${HASH_SALT}
      - apple_apn_key_id=${APPLE_APN_KEY_ID}
      - walletpass_token=${WALLETPASS_TOKEN}
      - sentry_dsn=${SENTRY_DSN}
      - google_issuer_id=${GOOGLE_ISSUER_ID}
      - reader_token=${READER_TOKEN}
    depends_on:
      - redis
    healthcheck:
      test: "curl --fail http://localhost:80/healtz || exit 1"
      interval: 60s
      timeout: 3s
      start_period: 20s
      retries: 5
  lockoff-reader:
    image: jensimik/lockoff-reader:latest
    container_name: lockoff-reader
    restart: always
    environment:
      - GPIOZERO_PIN_FACTORY=native
      # use lockoff-backend and ok to use http as inside the docker container virtual network
      # if using multi-doors and a reader on another host then use https
      - backend_url=http://lockoff-backend/reader-check-code
      - reader_token=${READER_TOKEN}
    group_add:
      - dialout
    devices:
      - /dev/OPTICON:/dev/OPTICON
      - /dev/DISPLAY:/dev/DISPLAY
      - /dev/gpiomem:/dev/gpiomem
    depends_on:
      - lockoff-backend
    healthcheck:
      test: "curl --fail http://localhost:80/healtz || exit 1"
      interval: 60s
      timeout: 3s
      start_period: 20s
      retries: 5
