version: "3.8"  
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: >
      --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} ping | grep PONG
      interval: 10s
      timeout: 3s
      retries: 5
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  lockoff:
    image: jensimik/lockoff:latest
    container_name: lockoff
    restart: always
    volumes:
      - $PWD/lockoff.db3:/db/lockoff.db3
      - $PWD/secret/secret:ro
    environment:
      - tz=Europe/Copenhagen
      - db_file=/db/lockoff.db3
      - klubmodul_base_url=${KLUBMODUL_BASE_URL}
      - klubmodul_username=${KLUBMODUL_USERNAME}
      - klubmodul_password=${KLUBMODUL_PASSWORD}
      - opticon_url=/dev/OPTICON
      - display_url=/dev/DISPLAY
      - redis_url=${REDIS_URL}
      - jwt_secret=${JWT_SECRET}
      - secret=${SECRET}
      - dl_secret=${DL_SECRET}
      - apple_key_password=${APPLE_KEY_PASSWORD}
      - GPIOZERO_PIN_FACTORY=native
      - admin_user_ids=${ADMIN_USER_IDS}
      - hash_salt=${HASH_SALT}
      - apple_apn_key_id=${APPLE_APN_KEY_ID}
      - walletpass_token=${WALLETPASS_TOKEN}
      - sentry_dsn=${SENTRY_DSN}
      - google_issuer_id=${GOOGLE_ISSUER_ID}
    group_add:
      - dialout
    devices:
      - /dev/OPTICON:/dev/OPTICON
      - /dev/DISPLAY:/dev/DISPLAY
      - /dev/gpiomem:/dev/gpiomem
    depends_on:
      - redis
    healthcheck:
      test: "curl --fail http://localhost:80/healtz || exit 1"
      interval: 60s
      timeout: 3s
      start_period: 20s
      retries: 5