# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: lockoff-backend

on:
  push:
    paths:
      - "backend/**/*"
      - ".github/workflows/backend.yml"
    branches:
      - main
  pull_request:
    paths:
      - "backend/**/*"
      - ".github/workflows/backend.yml"
    branches:
      - main

permissions:
  contents: read

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest anyio
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: "deploy to fly.io"
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
